import type { Project } from "../types";
import { oncallAutomationShared } from "./shared";

export const oncallAutomationEn: Project = {
  ...oncallAutomationShared,
  title: "Frontend On-Call Process Automation",
  period: "October 2025",
  role: "Identified inefficiency, designed and built the automation, drove team adoption",
  summary:
    "A set of n8n workflows that consolidates fragmented on-call work into a single board and automates the end-of-rotation report, reducing report-writing time to about a third of the original effort and creating an environment where on-call engineers can focus on their assigned issues.",
  background: {
    content: [
      "The frontend on-call role had quietly accumulated overhead across intake, reporting, and handover — friction the team worked around instead of through.",
    ],
  },
  problem: {
    content: [
      "**Fragmented intake:** on-call engineers had to monitor Shakebug and Slack separately, then manually decide what was worth tracking.",
      "**Manual handover report:** producing the end-of-rotation report required checking New Relic, OpsGenie, Shakebug, and Slack one by one and writing the summary by hand.",
      "**Unreliable unresolved-work handover:** the previous on-call engineer wrote a manual list of unfinished work for the next rotation. Items got dropped, and dropped items could sit untouched for months before anyone noticed.",
    ],
  },
  keyDecisions: [
    {
      title: "Consolidate intake into a single Jira board",
      description: [
        "Two input paths consolidated into a single Jira board, each handled by the right tool. Bugs reported via Shakebug flow through a shared Slack channel, where an n8n workflow uses tag-based filtering to identify team-relevant ones and auto-create Jira tickets. Bugs reported directly to the team Slack channel are captured via a Slack Workflow structured form and converted into Jira tickets.",
        "Each Jira ticket preserves the original Shakebug link and Slack-thread link for context. The on-call engineer monitors a single Jira board instead of multiple places.",
      ],
      media: [
        {
          type: "image",
          src: "/projects/oncall-automation/en/consolidation.svg",
          alt: "Before and after: fragmented intake from Shakebug and Slack consolidated into a single Jira board",
        },
      ],
    },
    {
      title: "Make the dual-system close explicit",
      description: [
        `Once bug tracking moved into Jira, closing a Jira ticket needed to also close the corresponding Shakebug ticket. Shakebug's API doesn't expose a 'close ticket' endpoint, so direct sync wasn't possible.`,
        `Design choice: instead of leaving the second close silently for the engineer to remember, surface it. When a Jira ticket is closed, an automated Slack message tags the closer to also close the Shakebug ticket — the dual action stays visible.`,
      ],
      media: [
        {
          type: "image",
          src: "/projects/oncall-automation/close-ticket-notice.png",
          alt: "Slack notification reminding the engineer to close the corresponding Shakebug ticket",
          caption: "Automated Slack reminder when a Jira ticket is closed",
        },
      ],
    },
    {
      title:
        "LLM-generated handover report with auto-reassigned unresolved work",
      description: [
        'The end-of-rotation report is generated by an n8n workflow that pulls from multiple platforms automatically: New Relic per-page SLIs analyzed and formatted by an LLM into a readable list, the week\'s Jira tickets classified as "closed this week" vs "unresolved" with LLM-generated summaries, and OpsGenie top-10 most-frequently-fired alerts.',
        "Unresolved Jira tickets are automatically reassigned to the next on-call engineer via Jira ticket reassignment, eliminating the manual-list step that used to drop items.",
      ],
      media: [
        {
          type: "image",
          src: "/projects/oncall-automation/en/report-flow.svg",
          alt: "End-of-rotation report flow: four platforms feed into n8n and LLM to produce a Slack report and auto-reassign tickets",
        },
        {
          type: "image",
          src: "/projects/oncall-automation/weekly-report.png",
          alt: "Generated weekly handover report showing top alerts, SLIs, and ticket summaries",
          caption: "Auto-generated end-of-rotation report posted to Slack",
        },
      ],
    },
  ],
  result: {
    content: [
      "**Time savings:** report-writing time reduced to about a third (~67% reduction).",
      "**Better focus:** on-call engineers now manage their assigned tickets on a single board, no longer juggling Shakebug, Slack, and platform-by-platform monitoring.",
      "**No more dropped work:** every unresolved ticket is now system-tracked and auto-reassigned at rotation, replacing the fragile manual list.",
      `**Cross-team adoption:** the bug-routing concept caught the QA team's attention. They built a parallel version using n8n workflow — routing tag-filtered bugs from a central Slack channel into team-specific channels, preserving the original thread link so on-call engineers could quickly find and continue conversations with reporters.`,
    ],
  },
};
